import type { HubScope } from './resolveScope';
import config from '@/data/first-visit-questions.json';

// Mirrors docs/first-visit-survey-questions.json (generated by
// scripts/build-fv-survey-config.py in the Onboarding_tool repo).
// Refresh locally: npm run sync-questions.

export type FieldType =
  | 'text'
  | 'select'
  | 'boolean'
  | 'number'
  | 'date'
  | 'file'
  | 'repeater';

export type Mode = 'data' | 'observe' | 'measure';
export type Status = 'existing' | 'proposed';

export type FirstVisitQuestion = {
  slug: string;
  label: string;
  description: string | null;
  scope: HubScope;
  mode: Mode;
  type: FieldType;
  options: string[];
  required: boolean;
  repeater: boolean;
  pms_target: string | null;
  status: Status;
  verdict: 'keep' | 'reword' | 'merge' | 'move' | null;
  notes: string | null;
  phase_id: string;
  phase_label: string;
};

export type FirstVisitPhase = {
  id: string;
  label: string;
  questions: FirstVisitQuestion[];
};

type RawConfig = {
  version: string;
  generated_at: string;
  source_file: string;
  counts: Record<string, number>;
  phases: FirstVisitPhase[];
};

const RAW = config as unknown as RawConfig;

// Many XLSX-source descriptions are operational notes for PMs, not guidance
// for the field inspector ("Pre-filled from ClickUp; PM only confirms",
// "From Final Info DB; auto-fillable", etc.). They add noise on the phone.
// Anything matching these patterns is stripped to null at load time so the
// UI only ever shows descriptions that actually help fill out the question.
const OPERATIONAL_DESCRIPTION_PATTERNS: RegExp[] = [
  /\bPM\b/,
  /clickup/i,
  /final info db/i,
  /auto[- ]?fill/i,
  /auto[- ]?generated/i,
  /pre[- ]?filled/i,
  /host faq/i,
  /\bdata point\b/i,
  /deals table/i,
  /validates_host_faq/i,
  /\bfv_/,
  /\[gaps/i,
  /resumable post-visit/i,
  /geoapify/i,
  /hub auto/i,
  /from hub\b/i,
  /^dropdown of/i,
];

function isOperationalDescription(d: string | null | undefined): boolean {
  if (!d) return false;
  return OPERATIONAL_DESCRIPTION_PATTERNS.some((p) => p.test(d));
}

function stripOperationalDescriptions(phases: FirstVisitPhase[]): FirstVisitPhase[] {
  return phases.map((p) => ({
    ...p,
    questions: p.questions.map((q) =>
      isOperationalDescription(q.description) ? { ...q, description: null } : q,
    ),
  }));
}

// Defensive dedup: the XLSX-driven generator can emit the same slug twice within
// a phase (content bug). Two rows sharing a slug would collide on the Dexie
// compound key [target_id+question_key+area_key] and produce duplicate React
// keys in the survey list. Resolution: keep the first occurrence per
// (phase_id, slug), promoting it to required:true if any duplicate is required.
// In dev we log a warning so the content issue stays visible. Production stays
// silent — bad data should never crash the app.
function dedupePhases(phases: FirstVisitPhase[]): FirstVisitPhase[] {
  return phases.map((p) => {
    const byKey = new Map<string, FirstVisitQuestion>();
    const dropped: string[] = [];
    for (const q of p.questions) {
      const key = q.slug;
      const existing = byKey.get(key);
      if (!existing) {
        byKey.set(key, q);
        continue;
      }
      // Already saw this slug in this phase. Promote required if either copy
      // is required, then drop the duplicate.
      if (q.required && !existing.required) {
        byKey.set(key, { ...existing, required: true });
      } else if (existing.required || q.required) {
        byKey.set(key, { ...existing, required: true });
      }
      dropped.push(key);
    }
    if (dropped.length > 0 && typeof process !== 'undefined' && process.env.NODE_ENV !== 'production') {
      // eslint-disable-next-line no-console
      console.warn(
        `[first-visit-questions] phase ${p.id} (${p.label}) has duplicate slug(s): ${dropped.join(', ')}. ` +
          `Kept first occurrence per slug (required-promoted). Fix the source XLSX or generator.`,
      );
    }
    return { ...p, questions: Array.from(byKey.values()) };
  });
}

export const PHASES: FirstVisitPhase[] = stripOperationalDescriptions(
  dedupePhases(RAW.phases),
);
export const ALL_QUESTIONS: FirstVisitQuestion[] = PHASES.flatMap((p) => p.questions);

// Counts are recomputed from the deduplicated PHASES so the metadata stays in
// sync with what the app actually renders. The original generator-provided
// counts live in CONFIG_META.raw_counts if a caller needs them.
export const CONFIG_META = {
  version: RAW.version,
  generated_at: RAW.generated_at,
  source_file: RAW.source_file,
  raw_counts: RAW.counts,
  counts: {
    ...RAW.counts,
    phases: PHASES.length,
    questions: ALL_QUESTIONS.length,
    existing: ALL_QUESTIONS.filter((q) => q.status === 'existing').length,
    proposed: ALL_QUESTIONS.filter((q) => q.status === 'proposed').length,
    with_verdict: ALL_QUESTIONS.filter((q) => q.verdict).length,
  },
};

// Return phases (in original order) with their questions filtered to a single
// scope. Drops phases that end up empty for the scope.
export function phasesForScope(scope: HubScope): FirstVisitPhase[] {
  return PHASES.map((p) => ({
    ...p,
    questions: p.questions.filter((q) => q.scope === scope),
  })).filter((p) => p.questions.length > 0);
}

export function questionsForScope(scope: HubScope): FirstVisitQuestion[] {
  return ALL_QUESTIONS.filter((q) => q.scope === scope);
}

// The DB column for this answer's grouping is `area_key`; we use the phase_id
// as that grouping. Centralised so write paths stay in sync with the config.
export function areaKeyFor(q: FirstVisitQuestion): string {
  return q.phase_id;
}
