import type { HubScope } from './resolveScope';
import config from '@/data/first-visit-questions.json';

// Mirrors docs/first-visit-survey-questions.json (generated by
// scripts/build-fv-survey-config.py in the Onboarding_tool repo).
// Refresh locally: npm run sync-questions.

export type FieldType =
  | 'text'
  | 'select'
  | 'boolean'
  | 'number'
  | 'date'
  | 'file'
  | 'repeater';

export type Mode = 'data' | 'observe' | 'measure';
export type Status = 'existing' | 'proposed';

export type FirstVisitQuestion = {
  slug: string;
  label: string;
  description: string | null;
  scope: HubScope;
  mode: Mode;
  type: FieldType;
  options: string[];
  required: boolean;
  repeater: boolean;
  pms_target: string | null;
  status: Status;
  verdict: 'keep' | 'reword' | 'merge' | 'move' | null;
  notes: string | null;
  phase_id: string;
  phase_label: string;
  // Optional block-repeater group identifier. Questions that share a
  // group_id render together inside a repeating block on the survey (e.g.
  // "check-in step", "equipment issue"). Property does not exist on the
  // generated JSON yet — WS-C will introduce it. Until then this is
  // always undefined and groupIdFor() returns null.
  group_id?: string | null;
  // Renders the question as a chip-style multi-select picker. Combined with
  // `options`, each option becomes a toggleable chip. WS-C will set this on
  // the JSON. Backwards-compatible: when undefined the legacy renderer is used.
  multi_select?: boolean;
  // When `multi_select` is true and this is true, an inline "+ Add custom"
  // input is rendered so the inspector can append free-text options to the
  // picker. The custom strings are stored in `value` exactly like standard
  // options — no separate field. Optional, WS-C populates this.
  allow_custom_options?: boolean;
  // Conditional follow-up field that appears below this question when its
  // value matches `when_value`. Used for boolean Yes/No follow-ups
  // ("Secondary fire exit available?" → "Where?") and select-value follow-ups.
  // Storage: the follow-up text lives as a sibling answer with synthetic
  // question_key `${parent.slug}__follow_up`, same target/area, same
  // step_index as the parent.
  follow_up?: {
    when_value: unknown;
    label: string;
    type: 'text' | 'number';
    required?: boolean;
  };
  // Per-option follow-up renderer for multi-select pickers. For each chip
  // the inspector selects, an inline labeled input appears below the picker
  // using `label_template` with `{option}` substituted. Storage: each
  // option's follow-up lives as a sibling answer with synthetic question_key
  // `${parent.slug}__per_option__${slugify(option)}` (no step_index).
  per_option_follow_up?: {
    label_template: string;
    type: 'text';
    required?: boolean;
  };
  // Slug of another question this one should render under (used by WS-F for
  // media anchoring). Renderer in WS-B does not act on this; it is here so
  // the type is ready for WS-F.
  anchor_to?: string;
};

export type FirstVisitPhase = {
  id: string;
  label: string;
  questions: FirstVisitQuestion[];
};

type RawConfig = {
  version: string;
  generated_at: string;
  source_file: string;
  counts: Record<string, number>;
  phases: FirstVisitPhase[];
};

const RAW = config as unknown as RawConfig;

// --- Phase A: dropped questions (review 2026-06-02) ---
// Bucket 1 + 9d cost fields (5) + 9e appliance condition fields (2),
// replaced by the unified Findings repeater. Fuse-box duplicates are dropped
// status-aware (see DROP_PROPOSED_DUP_SLUGS) so the existing rows survive.
export const DROPPED_SLUGS = new Set<string>([
  // Phase 2 — location & arrival (Hub auto-generates from Geoapify/Places)
  'fv_location_distance_to_center_min', 'fv_location_nearest_transport',
  'fv_location_directions_from_airport', 'fv_location_directions_from_central_station',
  'fv_tips_grocery', 'fv_tips_restaurants', 'fv_tips_attractions', 'fv_tips_nightlife',
  'fv_tips_markets', 'fv_route_closest_transit_station', 'fv_route_from_airport',
  'fv_route_from_central_station',
  // Phase 3 — building exterior
  'fv_building_elevator_instructions', 'fv_accessibility_elevator_dimensions',
  // Phase 4 — check-in
  'fv_checkin_guide_2_needed', 'fv_step_lock_notes',
  // Phase 5 — infrastructure / utilities (meter block + dup proposed)
  'fv_trash_onsite_check', 'fv_waste_separation_streams', 'fv_utility_provider',
  'fv_electricity_meter_location', 'fv_electric_meter_location', 'fv_electric_meter_number',
  'fv_gas_meter_location', 'fv_gas_meter_number', 'fv_water_meter_location',
  'fv_water_meter_number',
  // Phase 6 — services
  'fv_service_restrictions_observed', 'fv_house_rule',
  // Phase 8 — documentation
  'fv_floorplan_uploaded', 'fv_floorplan_onsite_attach',
  // Phase 10 — check-out
  'fv_checkout_standard_items', 'fv_checkout_key_return_method',
  'fv_checkout_key_return_location', 'fv_checkout_trash_disposal', 'fv_checkout_time',
  // Phase 9d cost fields — replaced by Findings €
  'fv_furniture_cost_estimate_eur', 'fv_equipment_cost_estimate_eur',
  'fv_bathroom_improvement_cost_eur', 'fv_maintenance_cost_estimate_eur',
  'fv_maintenance_details',
  // Phase 9e appliance condition — repeater becomes pure inventory
  'appliance.status', 'appliance.statusNote',
]);

// Fuse-box proposed duplicates: drop only the status==='proposed' copies.
const DROP_PROPOSED_DUP_SLUGS = new Set<string>([
  'fv_fusebox_location', 'fv_fusebox_reset_instructions',
]);

function dropQuestions(phases: FirstVisitPhase[]): FirstVisitPhase[] {
  return phases.map((p) => ({
    ...p,
    questions: p.questions.filter((q) => {
      if (DROPPED_SLUGS.has(q.slug)) return false;
      if (DROP_PROPOSED_DUP_SLUGS.has(q.slug) && q.status === 'proposed') return false;
      return true;
    }),
  }));
}

// Many XLSX-source descriptions are operational notes for PMs, not guidance
// for the field inspector ("Pre-filled from ClickUp; PM only confirms",
// "From Final Info DB; auto-fillable", etc.). They add noise on the phone.
// Anything matching these patterns is stripped to null at load time so the
// UI only ever shows descriptions that actually help fill out the question.
const OPERATIONAL_DESCRIPTION_PATTERNS: RegExp[] = [
  /\bPM\b/,
  /clickup/i,
  /final info db/i,
  /auto[- ]?fill/i,
  /auto[- ]?generated/i,
  /pre[- ]?filled/i,
  /host faq/i,
  /\bdata point\b/i,
  /deals table/i,
  /validates_host_faq/i,
  /\bfv_/,
  /\[gaps/i,
  /resumable post-visit/i,
  /geoapify/i,
  /hub auto/i,
  /from hub\b/i,
  /^dropdown of/i,
];

function isOperationalDescription(d: string | null | undefined): boolean {
  if (!d) return false;
  return OPERATIONAL_DESCRIPTION_PATTERNS.some((p) => p.test(d));
}

function stripOperationalDescriptions(phases: FirstVisitPhase[]): FirstVisitPhase[] {
  return phases.map((p) => ({
    ...p,
    questions: p.questions.map((q) =>
      isOperationalDescription(q.description) ? { ...q, description: null } : q,
    ),
  }));
}

// Some XLSX rows describe data that lives on the `deals` table itself (stampings
// like `deals.name`), not in the `data_points` model the survey reads from. They
// render as empty fields and duplicate info already shown elsewhere in the UI
// (e.g. the deal name is in the VisitNavigator header). Hide them entirely.
// Slugs listed here are dropped from PHASES; phases that empty out are removed.
const HIDDEN_DEAL_STAMPING_SLUGS = new Set<string>([
  'fv_visit_deal_name',
]);

function hideDealStampingQuestions(phases: FirstVisitPhase[]): FirstVisitPhase[] {
  return phases
    .map((p) => ({
      ...p,
      questions: p.questions.filter((q) => !HIDDEN_DEAL_STAMPING_SLUGS.has(q.slug)),
    }))
    .filter((p) => p.questions.length > 0);
}

// "verify" was a spec marker meaning "this is a data point the inspector should
// confirm against pre-filled hub data". It leaked into user-facing labels,
// phase labels, and descriptions. When nothing is pre-filled there is nothing
// to "verify", so the word is just confusing on the phone. Strip it from
// display strings only — slugs (DB keys like `fv_building_amenities_verify`)
// are untouched.
function cleanLabel(label: string): string {
  if (!label) return label;
  let out = label;
  // " & verify" → "" (e.g. "Unit identity & verify" → "Unit identity")
  out = out.replace(/\s*&\s*verify\b/gi, '');
  // trailing " verify" → "" (e.g. "Building amenities verify" → "Building amenities")
  out = out.replace(/\s+verify\s*$/gi, '');
  // collapse double spaces + trim
  out = out.replace(/\s{2,}/g, ' ').trim();
  return out;
}

function cleanDescription(desc: string | null): string | null {
  if (!desc) return desc;
  // standalone "verify" → "confirm" (case-insensitive, lowercase replacement)
  let out = desc.replace(/\bverify\b/gi, 'confirm');
  out = out.replace(/\s{2,}/g, ' ').trim();
  return out.length === 0 ? null : out;
}

function stripVerifyWord(phases: FirstVisitPhase[]): FirstVisitPhase[] {
  return phases.map((p) => ({
    ...p,
    label: cleanLabel(p.label),
    questions: p.questions.map((q) => ({
      ...q,
      label: cleanLabel(q.label),
      description: cleanDescription(q.description),
      phase_label: cleanLabel(q.phase_label),
    })),
  }));
}

// Defensive dedup: the XLSX-driven generator can emit the same slug twice within
// a phase (content bug). Two rows sharing a slug would collide on the Dexie
// compound key [target_id+question_key+area_key] and produce duplicate React
// keys in the survey list. Resolution: keep the first occurrence per
// (phase_id, slug), promoting it to required:true if any duplicate is required.
// In dev we log a warning so the content issue stays visible. Production stays
// silent — bad data should never crash the app.
function dedupePhases(phases: FirstVisitPhase[]): FirstVisitPhase[] {
  return phases.map((p) => {
    const byKey = new Map<string, FirstVisitQuestion>();
    const dropped: string[] = [];
    for (const q of p.questions) {
      const key = q.slug;
      const existing = byKey.get(key);
      if (!existing) {
        byKey.set(key, q);
        continue;
      }
      // Already saw this slug in this phase. Promote required if either copy
      // is required, then drop the duplicate.
      if (q.required && !existing.required) {
        byKey.set(key, { ...existing, required: true });
      } else if (existing.required || q.required) {
        byKey.set(key, { ...existing, required: true });
      }
      dropped.push(key);
    }
    if (dropped.length > 0 && typeof process !== 'undefined' && process.env.NODE_ENV !== 'production') {
      // eslint-disable-next-line no-console
      console.warn(
        `[first-visit-questions] phase ${p.id} (${p.label}) has duplicate slug(s): ${dropped.join(', ')}. ` +
          `Kept first occurrence per slug (required-promoted). Fix the source XLSX or generator.`,
      );
    }
    return { ...p, questions: Array.from(byKey.values()) };
  });
}

// --- Phase B: unified Findings repeater (review 2026-06-02 §5) ---
// One repeating "findings" block (the post-visit shopping-list + repairs model)
// injected at unit_category scope (phase 9d, Unit walkthrough) and at location
// scope (phase 5, Building infrastructure & utilities). Replaces the dropped
// 9d cost fields and 9e appliance-condition fields (see DROPPED_SLUGS).
const UNIT_WALKTHROUGH_PHASE_ID = '9d';
const BUILDING_INFRA_PHASE_ID = '5';

const FINDING_CATEGORY_OPTIONS = ['Furniture','Appliance','Equipment','Bathroom','Structural/Building','Consumable','Other'];
const FINDING_LOCATION_OPTIONS = ['Kitchen','Bathroom','Bedroom','Living room','Hallway','Balcony','Building/common','Other'];
const FINDING_RESOLUTION_OPTIONS = ['Buy new (add)','Replace','Repair','Deep clean'];
const FINDING_URGENCY_OPTIONS = ['Blocks go-live','Nice-to-have'];

function makeFindingQuestions(scope: HubScope, phaseId: string, phaseLabel: string): FirstVisitQuestion[] {
  const base = { scope, mode: 'observe' as Mode, status: 'proposed' as Status, verdict: null,
    notes: null, repeater: true, group_id: 'finding', phase_id: phaseId, phase_label: phaseLabel };
  const q = (slug: string, label: string, type: FieldType, required: boolean,
    options: string[] = []): FirstVisitQuestion => ({ ...base, slug, label, description: null, type, required, options, pms_target: null });
  return [
    q('finding_item_name','Item / issue (clear name)','text',true),
    q('finding_category','Category','select',true,FINDING_CATEGORY_OPTIONS),
    q('finding_location','Location in unit','select',false,FINDING_LOCATION_OPTIONS),
    q('finding_resolution','Resolution','select',true,FINDING_RESOLUTION_OPTIONS),
    q('finding_quantity','Quantity','number',false),
    q('finding_cost_estimate_eur','Cost estimate (€)','number',true),
    q('finding_urgency','Urgency','select',false,FINDING_URGENCY_OPTIONS),
    q('finding_notes','Notes','text',false),
    q('finding_media','Photo / video','file',true),
  ];
}

function injectFindings(phases: FirstVisitPhase[]): FirstVisitPhase[] {
  return phases.map((p) => {
    if (p.id === UNIT_WALKTHROUGH_PHASE_ID) return { ...p, questions: [...p.questions, ...makeFindingQuestions('unit_category', p.id, p.label)] };
    if (p.id === BUILDING_INFRA_PHASE_ID) return { ...p, questions: [...p.questions, ...makeFindingQuestions('location', p.id, p.label)] };
    return p;
  });
}

// --- Phase E: Bucket-2 config fixes (review 2026-06-02) ---
// Two generic helpers drive all eight changes so we don't write a bespoke
// transform per fix:
//   overrideQuestions   — shallow-merge a Partial<FirstVisitQuestion> patch
//                         into every question whose slug matches.
//   injectBucket2Questions — append brand-new questions to a specific phase
//                         (same pattern as injectFindings).

// Shallow-merge `patchMap[slug]` into each matching question across all phases.
// Slugs in the map that match no question are silently no-ops (reported in the
// Phase E summary, not enforced here — keeps the helper generic).
export function overrideQuestions(
  phases: FirstVisitPhase[],
  patchMap: Record<string, Partial<FirstVisitQuestion>>,
): FirstVisitPhase[] {
  return phases.map((p) => ({
    ...p,
    questions: p.questions.map((q) =>
      patchMap[q.slug] ? ({ ...q, ...patchMap[q.slug] } as FirstVisitQuestion) : q,
    ),
  }));
}

// Build a single new question with sane Phase-E defaults (proposed status,
// non-repeater, no pms_target unless overridden). Mirrors makeFindingQuestions'
// `q` builder so injected rows are shaped like the generated ones.
function makeBucket2Question(
  phase: FirstVisitPhase,
  scope: HubScope,
  partial: Partial<FirstVisitQuestion> & Pick<FirstVisitQuestion, 'slug' | 'label' | 'type'>,
): FirstVisitQuestion {
  return {
    description: null,
    scope,
    mode: 'observe',
    options: [],
    required: false,
    repeater: false,
    pms_target: null,
    status: 'proposed',
    verdict: null,
    notes: null,
    phase_id: phase.id,
    phase_label: phase.label,
    ...partial,
  };
}

function injectBucket2Questions(phases: FirstVisitPhase[]): FirstVisitPhase[] {
  return phases.map((p) => {
    // E2 + E3 — parking phase (id '3'), location scope.
    if (p.id === '3') {
      const additions: FirstVisitQuestion[] = [
        makeBucket2Question(p, 'location', {
          slug: 'fv_parking_spot_number',
          label: 'Exact parking spot number',
          type: 'text',
          required: false,
        }),
        makeBucket2Question(p, 'location', {
          slug: 'fv_photo_parking_spot',
          label: 'Photo of the parking spot',
          type: 'file',
          required: true,
          anchor_to: 'fv_parking_dedicated_spots',
        }),
      ];
      return { ...p, questions: [...p.questions, ...additions] };
    }
    // E6 — fuse box media, infrastructure phase (id '5'), location scope.
    if (p.id === '5') {
      const additions: FirstVisitQuestion[] = [
        makeBucket2Question(p, 'location', {
          slug: 'fv_video_fusebox',
          label: 'Fuse box video (reset/operation)',
          type: 'file',
          required: false,
          anchor_to: 'fv_fusebox_location',
        }),
        makeBucket2Question(p, 'location', {
          slug: 'fv_photo_fusebox_location',
          label: 'Photo of fuse box location',
          type: 'file',
          required: false,
          anchor_to: 'fv_fusebox_location',
        }),
      ];
      return { ...p, questions: [...p.questions, ...additions] };
    }
    return p;
  });
}

// Patch map for the override-driven Phase E changes (E1, E3, E4, E5, E7, E8).
const BUCKET2_OVERRIDES: Record<string, Partial<FirstVisitQuestion>> = {
  // E1 — building amenities: multi-select + custom, fixed option list.
  fv_building_amenities_verify: {
    multi_select: true,
    allow_custom_options: true,
    options: [
      'Aufzug',
      'Gemeinschafts Balkon/Terrasse',
      'Gemeinschaftsgarten',
      'Schwimmbad',
      'Sauna',
      'Fitnessraum',
      'Konferenzräume',
      'Reception/Concierge',
    ],
  },
  // E3 — underground garage clearance height as a conditional follow-up on the
  // parking-type select. Triggered by the on-site garage option.
  fv_parking_actual_type: {
    follow_up: {
      when_value: 'Garage on-site',
      label: 'Underground garage clearance height (cm)',
      type: 'number',
      required: false,
    },
  },
  // E4 — lock brand collected once per unit: out of the checkin_step repeater,
  // promoted to unit_category scope.
  fv_step_lock_brand: {
    group_id: null,
    scope: 'unit_category',
  },
  // E5 — capacity fields always collected: clear the "Only if..." conditional
  // gate that lived purely in the description text.
  fv_capacity_actual_setup: { description: null },
  fv_capacity_comments: { description: null },
  // E7 — common areas: append two shared-space options to the existing list.
  fv_common_area: {
    options: ['Lobby', 'Rooftop', 'Courtyard', 'SmokingArea', 'Storage', 'Other', 'Shared kitchen', 'Shared garden'],
  },
  // E8 — media anchoring: each media question renders under its topic question.
  fv_video_trash_location: { anchor_to: 'fv_trash_container_location' },
  fv_photo_storage_room: { anchor_to: 'fv_storage_location' },
  fv_video_parking_access: { anchor_to: 'fv_parking_access_instructions' },
  fv_photo_fusebox: { anchor_to: 'fv_fusebox_location' },
  fv_video_checkin_walkthrough: { anchor_to: 'fv_step_name' },
};

export const PHASES: FirstVisitPhase[] = stripVerifyWord(
  stripOperationalDescriptions(
    hideDealStampingQuestions(
      overrideQuestions(
        injectBucket2Questions(injectFindings(dropQuestions(dedupePhases(RAW.phases)))),
        BUCKET2_OVERRIDES,
      ),
    ),
  ),
);
export const ALL_QUESTIONS: FirstVisitQuestion[] = PHASES.flatMap((p) => p.questions);

// Counts are recomputed from the deduplicated PHASES so the metadata stays in
// sync with what the app actually renders. The original generator-provided
// counts live in CONFIG_META.raw_counts if a caller needs them.
export const CONFIG_META = {
  version: RAW.version,
  generated_at: RAW.generated_at,
  source_file: RAW.source_file,
  raw_counts: RAW.counts,
  counts: {
    ...RAW.counts,
    phases: PHASES.length,
    questions: ALL_QUESTIONS.length,
    existing: ALL_QUESTIONS.filter((q) => q.status === 'existing').length,
    proposed: ALL_QUESTIONS.filter((q) => q.status === 'proposed').length,
    with_verdict: ALL_QUESTIONS.filter((q) => q.verdict).length,
  },
};

// Return phases (in original order) with their questions filtered to a single
// scope. Drops phases that end up empty for the scope.
export function phasesForScope(scope: HubScope): FirstVisitPhase[] {
  return PHASES.map((p) => ({
    ...p,
    questions: p.questions.filter((q) => q.scope === scope),
  })).filter((p) => p.questions.length > 0);
}

export function questionsForScope(scope: HubScope): FirstVisitQuestion[] {
  return ALL_QUESTIONS.filter((q) => q.scope === scope);
}

// The DB column for this answer's grouping is `area_key`; we use the phase_id
// as that grouping. Centralised so write paths stay in sync with the config.
export function areaKeyFor(q: FirstVisitQuestion): string {
  return q.phase_id;
}

// Returns the block-repeater group this question belongs to, or null when the
// question is not part of a repeater. The `group_id` property is not yet
// present on the generated JSON config — WS-C will add it — so this currently
// always returns null in production. Callers can treat null as "single
// instance, no step_index needed".
export function groupIdFor(q: FirstVisitQuestion): string | null {
  return q.group_id ?? null;
}

// WS-F media anchoring: photo/video file questions opt into rendering inline
// underneath their related data question by setting `anchor_to: <slug>` in
// the JSON config. The two helpers below let UnitSurvey pull anchored
// questions out of their original phase and inline them under the anchor.
//
// `buildAnchorMap` collects file questions keyed by their anchor's slug.
// `filterOutAnchored` removes anchored questions from their original phase
// (only when the anchor target also exists in the same scope — orphans stay
// put so they aren't silently dropped). Phases that empty out are removed,
// matching `phasesForScope`'s behaviour.
export function buildAnchorMap(
  questions: FirstVisitQuestion[],
): Map<string, FirstVisitQuestion[]> {
  const all = new Set(questions.map((q) => q.slug));
  const map = new Map<string, FirstVisitQuestion[]>();
  for (const q of questions) {
    const target = q.anchor_to;
    if (!target) continue;
    if (!all.has(target)) continue; // orphan — leave in place
    const bucket = map.get(target);
    if (bucket) bucket.push(q);
    else map.set(target, [q]);
  }
  return map;
}

export function filterOutAnchored(
  phases: FirstVisitPhase[],
  anchoredSlugs: Set<string>,
): FirstVisitPhase[] {
  return phases
    .map((p) => ({
      ...p,
      questions: p.questions.filter((q) => !anchoredSlugs.has(q.slug)),
    }))
    .filter((p) => p.questions.length > 0);
}
