// Authoritative source for the First-Visit V1 Redesign question set.
// One entry per survey question (Notion DB "First-Visit Survey — V1 Redesign").
// `scripts/redesign/gen.mjs` splits these into editor content + structural overlay.
//
// Field conventions (defaults filled by the generator, omit when default):
//   scope: 'deal' | 'location' | 'unit_category'
//   type:  text | select | boolean | number | date | file
//   multi_select / allow_custom_options : content (chip pickers)
//   group_id      : repeater membership (checkin_step | issue | item)
//   visible_when  : conditional gate {question, equals|not_equals|in|not_in}
//   mode:'observe': media questions (cosmetic, matches prior convention)
//   pms_target    : left null across the board — PMS mapping is a hub follow-up.

const YESNO = ['Yes', 'No'];

export const VERSION = '2026-06-25-redesign-v1';

export const PHASES = [
  // ── 1 · Visit metadata (deal) ───────────────────────────────────────────
  { id: '1', label: 'Visit metadata', scope: 'deal', questions: [
    { slug: 'fv_visit_date', label: 'Date of visit', type: 'date', required: true },
    { slug: 'fv_visit_visitor_name', label: 'Visitor name', type: 'text', required: true },
  ]},

  // ── 2 · Location & neighbourhood (location) ──────────────────────────────
  { id: '2', label: 'Location & neighbourhood', scope: 'location', questions: [
    { slug: 'fv_location_quality', label: 'Location quality for guests', type: 'select',
      options: ['Excellent', 'Good', 'Acceptable', 'Poor'], required: true,
      description: 'What to consider: connection to public transport; vicinity to city centre; vicinity to landmarks; offering of restaurants/bars/supermarkets nearby.' },
    { slug: 'fv_location_safety_concern', label: 'Location safety concern', type: 'select',
      options: ['No', 'Minor', 'Yes (explain)'], required: true },
    { slug: 'fv_neighbourhood_narrative', label: 'Neighbourhood narrative (3-5 sentences)', type: 'text',
      required: true, description: 'Can be AI pre-filled from the address, then PM confirms/edits.' },
    { slug: 'fv_neighbourhood_vibe_tags', label: 'Neighbourhood vibe tags', type: 'select', multi_select: true,
      options: ['Residential', 'Touristy', 'Nightlife', 'Family-friendly', 'Business', 'Bohemian', 'Quiet', 'Lively', 'Mixed-use', 'Up-and-coming'], required: false },
    { slug: 'fv_best_for_guest_type', label: 'Best for guest type', type: 'select', multi_select: true,
      options: ['Business', 'Families', 'Couples', 'Groups', 'Solo', 'Long-stay'], required: true },
    { slug: 'fv_location_notes', label: 'Location notes', type: 'text', required: false },
  ]},

  // ── 3 · Building exterior & parking (location) ───────────────────────────
  { id: '3', label: 'Building exterior & parking', scope: 'location', questions: [
    { slug: 'fv_parking_actual_type', label: 'Is there parking at the property?', type: 'select',
      options: ['On-prem free', 'On-prem paid', 'Garage on-site', 'Garage nearby', 'None'], required: true,
      description: 'Gate: when "None", all parking sub-questions collapse.' },
    { slug: 'fv_parking_dedicated_spots', label: 'Number of dedicated spots', type: 'number', required: false,
      visible_when: { question: 'fv_parking_actual_type', not_in: ['None'] } },
    { slug: 'fv_parking_spot_number', label: 'Exact parking spot number', type: 'text', required: false,
      visible_when: { question: 'fv_parking_actual_type', not_in: ['None'] } },
    { slug: 'fv_parking_access_instructions', label: 'Parking access instructions', type: 'text', required: false,
      visible_when: { question: 'fv_parking_actual_type', not_in: ['None'] } },
    { slug: 'fv_photo_parking_spot', label: 'Photo of the parking spot', type: 'file', mode: 'observe', required: false,
      visible_when: { question: 'fv_parking_actual_type', not_in: ['None'] } },
    { slug: 'fv_video_parking_access', label: 'Parking access video', type: 'file', mode: 'observe', required: false,
      visible_when: { question: 'fv_parking_actual_type', not_in: ['None'] } },
    { slug: 'fv_parking_bike_available', label: 'Bike parking available?', type: 'boolean', options: YESNO, required: true },
    { slug: 'fv_parking_nearby_options', label: 'Nearby parking options', type: 'text', required: false,
      description: 'AI-generated from the address; PM validates/regenerates.' },
    { slug: 'fv_building_state', label: 'Building state', type: 'select',
      options: ['Excellent', 'Good', 'Acceptable', 'Needs attention', 'Poor'], required: true,
      description: 'What to look at: facade condition; entrance/lobby cleanliness; visible damage or wear; lighting; signs of disrepair.' },
    { slug: 'fv_building_mold', label: 'Mold visible in building?', type: 'select',
      options: ['No', 'Yes-minor', 'Yes-significant'], required: true },
    { slug: 'fv_building_hallways_clean', label: 'Hallways clean?', type: 'boolean', options: YESNO, required: true },
    { slug: 'fv_building_construction_nearby', label: 'Construction site/disruption nearby?', type: 'boolean',
      options: ['No', 'Yes'], required: true },
    { slug: 'fv_building_amenities_verify', label: 'Building amenities', type: 'select', multi_select: true, allow_custom_options: true,
      options: ['Aufzug', 'Gemeinschafts Balkon/Terrasse', 'Gemeinschaftsgarten', 'Schwimmbad', 'Sauna', 'Fitnessraum', 'Konferenzräume', 'Reception/Concierge', 'None'], required: true },
    { slug: 'fv_accessibility_step_free_entry', label: 'Step-free entry to the building?', type: 'select',
      options: ['Yes', 'No', 'Partial'], required: false },
    { slug: 'fv_accessibility_ramps', label: 'Ramps / accessibility aids present?', type: 'text', required: false },
    { slug: 'fv_accessibility_notes', label: 'Other accessibility / mobility notes', type: 'text', required: false },
    { slug: 'fv_building_elevator_present', label: 'Is there an elevator?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate: when "No", elevator sub-questions collapse.' },
    { slug: 'fv_building_elevator_working', label: 'Elevator working today?', type: 'select',
      options: ['Yes', 'No', 'Partially'], required: false,
      visible_when: { question: 'fv_building_elevator_present', equals: true } },
    { slug: 'fv_building_elevator_size', label: 'Elevator estimated size / capacity', type: 'select',
      options: ['Small (1-2 persons)', 'Medium (3-4)', 'Large (5+ / goods)'], required: false,
      visible_when: { question: 'fv_building_elevator_present', equals: true } },
    { slug: 'fv_building_elevator_condition', label: 'Elevator condition', type: 'select',
      options: ['Excellent', 'Good', 'Acceptable', 'Needs attention', 'Poor'], required: false,
      description: 'What to look at: cleanliness, lighting, signs of wear/faults, smoothness of operation.',
      visible_when: { question: 'fv_building_elevator_present', equals: true } },
  ]},

  // ── 4 · Building access & check-in (location) ────────────────────────────
  { id: '4', label: 'Building access & check-in', scope: 'location', questions: [
    { slug: 'fv_step_name', label: 'Check-in step name', type: 'text', required: true, group_id: 'checkin_step',
      description: 'Free-text per step; repeatable — all per-step fields below repeat for each step.' },
    { slug: 'fv_step_access_point', label: 'Access point', type: 'select',
      options: ['Main Gate', 'Building Door', 'Apartment Door', 'Other'], required: true, group_id: 'checkin_step' },
    { slug: 'fv_step_lock_type', label: 'Lock type', type: 'select',
      options: ['Smart Lock', 'Keypad', 'Ring To Open', 'Call To Open', 'Chip', 'Physical Key'], required: true, group_id: 'checkin_step' },
    { slug: 'fv_step_smart_lock_provider', label: 'Smart lock provider', type: 'select',
      options: ['Nuki', 'Akiles', 'Bold', 'RemoteLock', 'Salto', 'EVVA', 'Other'], required: false, group_id: 'checkin_step' },
    { slug: 'fv_step_smart_lock_device_id', label: 'Smart lock device ID / serial', type: 'text', required: false, group_id: 'checkin_step' },
    { slug: 'fv_step_lock_brand', label: 'Lock brand / manufacturer', type: 'text', required: false, group_id: 'checkin_step' },
    { slug: 'fv_step_lock_classification', label: 'Lock classification', type: 'select',
      options: ['Primary', 'Backup'], required: true, group_id: 'checkin_step' },
    { slug: 'fv_step_key_storage_method', label: 'Key storage method', type: 'select',
      options: ['Keybox', 'Locker', 'Human handover'], required: false, group_id: 'checkin_step' },
    { slug: 'fv_step_storage_brand', label: 'Storage brand', type: 'text', required: false, group_id: 'checkin_step' },
    { slug: 'fv_step_default_access_code', label: 'Default access code', type: 'text', required: false, group_id: 'checkin_step' },
    { slug: 'fv_video_checkin_walkthrough', label: 'Check-in walkthrough video', type: 'file', mode: 'observe', required: true },
    { slug: 'fv_checkin_notes_overall', label: 'Overall check-in notes (not per-step)', type: 'text', required: false },
    { slug: 'fv_checkin_complexity', label: 'Check-in complexity overall', type: 'select',
      options: ['Simple', 'Moderate', 'Complex'], required: true,
      description: 'What to weigh: number of access steps; number of locks/codes; whether a human handover is needed; signage clarity; distance from entrance to unit.' },
  ]},

  // ── 5 · Building infrastructure & services (location) ────────────────────
  { id: '5', label: 'Building infrastructure & services', scope: 'location', questions: [
    { slug: 'fv_storage_onsite_check', label: 'Luggage storage on-site?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate: when "No", storage sub-questions collapse.' },
    { slug: 'fv_storage_location', label: 'Storage location', type: 'select',
      options: ['In-apartment', 'Cellar', 'Corridor', 'Separate room', 'Other'], required: false,
      visible_when: { question: 'fv_storage_onsite_check', equals: true } },
    { slug: 'fv_storage_access_instructions', label: 'Storage access instructions for guest', type: 'text', required: false,
      visible_when: { question: 'fv_storage_onsite_check', equals: true } },
    { slug: 'fv_photo_storage_room', label: 'Storage room photo', type: 'file', mode: 'observe', required: false,
      visible_when: { question: 'fv_storage_onsite_check', equals: true } },
    { slug: 'fv_storage_comments', label: 'Storage comments', type: 'text', required: false,
      visible_when: { question: 'fv_storage_onsite_check', equals: true } },
    { slug: 'fv_trash_area_present', label: 'Is there a designated trash area?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate for the trash block.' },
    { slug: 'fv_trash_container_location', label: 'Trash container location', type: 'select',
      options: ['Backyard', 'Courtyard', 'Basement', 'Ground floor room', 'Street', 'Inside apartment'], required: false,
      visible_when: { question: 'fv_trash_area_present', equals: true } },
    { slug: 'fv_trash_handler', label: 'Trash handled by', type: 'select',
      options: ['CSP', 'Building management', 'Guest', 'Arbio team'], required: false,
      visible_when: { question: 'fv_trash_area_present', equals: true } },
    { slug: 'fv_trash_pickup_schedule', label: 'Pickup schedule', type: 'text', required: false,
      visible_when: { question: 'fv_trash_area_present', equals: true } },
    { slug: 'fv_trash_guest_instructions', label: 'Guest trash instructions (how guests dispose of trash)', type: 'text', required: false,
      description: 'Always asked — guests need disposal guidance regardless of an on-site container.' },
    { slug: 'fv_video_trash_location', label: 'Trash location photo/video', type: 'file', mode: 'observe', required: false,
      visible_when: { question: 'fv_trash_area_present', equals: true } },
    { slug: 'fv_fusebox_present', label: 'Is there a central/building fuse box?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate (building-level). The same question repeats per unit (see Unit safety).' },
    { slug: 'fv_fusebox_location', label: 'Fuse box location (building)', type: 'text', required: false,
      visible_when: { question: 'fv_fusebox_present', equals: true } },
    { slug: 'fv_fusebox_access', label: 'Fuse box access (building)', type: 'select',
      options: ['Guest can access', 'Staff/technician only'], required: false,
      visible_when: { question: 'fv_fusebox_present', equals: true } },
    { slug: 'fv_fusebox_reset_instructions', label: 'Fuse box reset instructions (building)', type: 'text', required: false,
      visible_when: { question: 'fv_fusebox_present', equals: true } },
    { slug: 'fv_video_fusebox', label: 'Fuse box video — location + reset (building)', type: 'file', mode: 'observe', required: false,
      visible_when: { question: 'fv_fusebox_present', equals: true } },
    { slug: 'fv_fire_safety_present', label: 'Is there central/building fire safety?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate (building-level): central extinguishers, marked exits, detectors. Repeats per unit.' },
    { slug: 'fv_fire_exit_secondary', label: 'Secondary fire exit available?', type: 'boolean', options: YESNO, required: false,
      visible_when: { question: 'fv_fire_safety_present', equals: true } },
    { slug: 'fv_fire_exit_route_notes', label: 'Fire exit route notes', type: 'text', required: false,
      visible_when: { question: 'fv_fire_safety_present', equals: true } },
    { slug: 'fv_fire_safety_concerns', label: 'Fire safety concerns observed (building-level)', type: 'select',
      options: ['None', 'Blocked exit', 'Faulty wiring', 'Flammable storage', 'Other'], required: false,
      visible_when: { question: 'fv_fire_safety_present', equals: true } },
    { slug: 'fv_video_fire_exit', label: 'Fire exit route — video walkthrough', type: 'file', mode: 'observe', required: false,
      visible_when: { question: 'fv_fire_safety_present', equals: true } },
    { slug: 'fv_photo_fire_safety', label: 'Fire safety photos (extinguisher, exits, detectors)', type: 'file', mode: 'observe', required: false,
      visible_when: { question: 'fv_fire_safety_present', equals: true } },
    { slug: 'fv_common_area', label: 'Common areas / building facilities', type: 'select', multi_select: true, allow_custom_options: true,
      options: ['Lobby', 'Rooftop', 'Courtyard', 'SmokingArea', 'Storage', 'Shared kitchen', 'Shared garden', 'Other', 'None'], required: false },
  ]},

  // ── 6 · Cleaning & laundry (location) ────────────────────────────────────
  { id: '6', label: 'Cleaning & laundry', scope: 'location', questions: [
    { slug: 'fv_cleaning_setup', label: 'Cleaning setup', type: 'select',
      options: ['External provider', 'In-house', 'Owner self-managed', 'Not yet set up'], required: true },
    { slug: 'fv_laundry_setup', label: 'Laundry setup', type: 'select',
      options: ['External delivery', 'In-house machines', 'Cleaning provider', 'Not yet set up'], required: true,
      description: 'Gate: delivery frequency shows unless "Not yet set up".' },
    { slug: 'fv_laundry_delivery_frequency', label: 'Laundry delivery frequency', type: 'text', required: false,
      visible_when: { question: 'fv_laundry_setup', not_equals: 'Not yet set up' } },
    { slug: 'fv_laundry_nearest_laundromat', label: 'Nearest laundromat for guests', type: 'text', required: false },
    { slug: 'fv_extra_services_offered', label: 'Extra services offered', type: 'select', multi_select: true,
      options: ['Early check-in', 'Late check-out', 'Express cleaning', 'Baby bed', 'High chair', 'Parking', 'Breakfast', 'Airport transfer', 'None'], required: true },
  ]},

  // ── 7 · WiFi (location) ──────────────────────────────────────────────────
  { id: '7', label: 'WiFi', scope: 'location', questions: [
    { slug: 'fv_wifi_present', label: 'Wi-Fi available?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate: when "No", WiFi sub-questions collapse.' },
    { slug: 'fv_wifi_ssid', label: 'WiFi network name (SSID)', type: 'text', required: false,
      visible_when: { question: 'fv_wifi_present', equals: true } },
    { slug: 'fv_wifi_password', label: 'WiFi password', type: 'text', required: false,
      visible_when: { question: 'fv_wifi_present', equals: true } },
    { slug: 'fv_wifi_download_speed_mbps', label: 'WiFi download speed (Mbps)', type: 'number', required: false,
      visible_when: { question: 'fv_wifi_present', equals: true } },
    { slug: 'fv_wifi_upload_speed_mbps', label: 'WiFi upload speed (Mbps)', type: 'number', required: false,
      visible_when: { question: 'fv_wifi_present', equals: true } },
    { slug: 'fv_wifi_router_location', label: 'WiFi router physical location', type: 'text', required: false,
      visible_when: { question: 'fv_wifi_present', equals: true } },
    { slug: 'fv_wifi_guest_router_access', label: 'Guest access to router?', type: 'boolean', options: YESNO, required: false,
      visible_when: { question: 'fv_wifi_present', equals: true } },
  ]},

  // ── 8 · Unit identity (unit_category) ────────────────────────────────────
  { id: '8', label: 'Unit identity', scope: 'unit_category', questions: [
    { slug: 'fv_unit_floor_number', label: 'Floor of unit', type: 'text', required: true },
    { slug: 'fv_unit_location_in_building', label: 'Unit number / location (e.g. links · rechts · Mitte)', type: 'text', required: false },
    { slug: 'fv_unit_type_check', label: 'Unit type', type: 'select',
      options: ['Apartment', 'Studio', 'Loft', 'Maisonette', 'Other'], required: true },
    // Kept with the identity block (after unit type) so the p8_identity voice
    // prompt's fields are contiguous below the prompt — no unrelated questions
    // wedged between the prompt and the fields it fills.
    { slug: 'fv_apartment_category', label: 'Apartment category', type: 'select',
      options: ['Premium', 'Standard', 'Midscale', 'Below standard'], required: true,
      description: 'Tiers anchored on finish quality, furnishing completeness, size and amenities — validate definitions with GX.' },
    { slug: 'fv_unit_balcony_present', label: 'Is there a balcony?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate: when "No", balcony count collapses.' },
    { slug: 'fv_unit_balconies_count', label: 'Number of balconies', type: 'number', required: false,
      visible_when: { question: 'fv_unit_balcony_present', equals: true } },
    { slug: 'fv_view_actual', label: 'Unit view', type: 'select',
      options: ['Busy street', 'Quiet side street', 'City square', 'Courtyard', 'Monument', 'Park', 'Waterfront', 'Other'], required: false },
    { slug: 'fv_view_comments', label: 'View comments', type: 'text', required: false },
    { slug: 'fv_location_noise_level', label: 'Noise heard with windows closed?', type: 'select',
      options: ['No', 'Yes-not disturbing', 'Yes-occasionally', 'Yes-regularly'], required: true,
      description: 'Gate: noise source shows unless "No".' },
    { slug: 'fv_location_noise_source', label: 'Noise source', type: 'select',
      options: ['Street', 'Tram/train', 'Neighbors', 'Construction', 'Aircraft', 'Other'], required: false,
      visible_when: { question: 'fv_location_noise_level', not_equals: 'No' } },
    // Non-voiced precise measurement (manual tap, see section-voice-prompts) —
    // parked at the end so it doesn't interrupt the view/noise voiced block.
    { slug: 'fv_accessibility_unit_door_widths', label: 'Apartment + bathroom door clear widths', type: 'text', required: false },
  ]},

  // ── 9 · Unit capacity (unit_category) ────────────────────────────────────
  { id: '9', label: 'Unit capacity', scope: 'unit_category', questions: [
    { slug: 'fv_capacity_base', label: 'Base capacity (standard beds)', type: 'number', required: true },
    { slug: 'fv_capacity_max', label: 'Max capacity (incl. sofa beds/extra)', type: 'number', required: true },
    { slug: 'fv_capacity_actual_setup', label: 'Capacity / bed setup notes', type: 'text', required: false },
    { slug: 'fv_capacity_comments', label: 'Capacity comments', type: 'text', required: false },
  ]},

  // ── 10 · Unit condition & issues (unit_category) ─────────────────────────
  { id: '10', label: 'Unit condition & issues', scope: 'unit_category', questions: [
    { slug: 'fv_furniture_status', label: 'Furnished to Arbio standard?', type: 'select',
      options: ['Yes fully', 'Mostly', 'No significant', 'No overhaul'], required: true,
      description: 'Arbio standard: required furniture set (bed, seating, dining, storage), condition/quality, completeness vs the checklist — validate with GX.' },
    { slug: 'fv_equipment_status', label: 'Equipment status', type: 'select',
      options: ['Meets standard', 'Minor additions', 'Significant additions'], required: true,
      description: 'Against the equipment checklist: kitchen equipment completeness, appliances working, essentials present.' },
    { slug: 'fv_bathroom_condition', label: 'Bathroom condition', type: 'select',
      options: ['Excellent', 'Good', 'Needs minor', 'Needs renovation'], required: true,
      description: 'What excellent means: cleanliness; fixtures working; sealing/grout intact; ventilation; no mold or leaks.' },
    { slug: 'fv_issues_found', label: 'Any issues found in the unit?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate for the unified issue log.' },
    { slug: 'issue_name', label: 'Issue / item name', type: 'text', required: true, group_id: 'issue',
      description: 'Repeat the block per issue.', visible_when: { question: 'fv_issues_found', equals: true } },
    { slug: 'issue_type', label: 'Issue type', type: 'select',
      options: ['Furniture', 'Equipment', 'Maintenance', 'Other'], required: true, group_id: 'issue',
      visible_when: { question: 'fv_issues_found', equals: true } },
    { slug: 'issue_location', label: 'Location in unit', type: 'select',
      options: ['Kitchen', 'Bathroom', 'Bedroom', 'Living room', 'Hallway', 'Balcony', 'Building/common', 'Other'], required: false, group_id: 'issue',
      visible_when: { question: 'fv_issues_found', equals: true } },
    { slug: 'issue_resolution', label: 'Resolution', type: 'select',
      options: ['Buy', 'Fix', 'Replace', 'Monitor'], required: true, group_id: 'issue',
      visible_when: { question: 'fv_issues_found', equals: true } },
    { slug: 'issue_quantity', label: 'Quantity', type: 'number', required: false, group_id: 'issue',
      visible_when: { question: 'fv_issues_found', equals: true } },
    { slug: 'issue_cost_estimate_eur', label: 'Cost estimate (€)', type: 'number', required: false, group_id: 'issue',
      visible_when: { question: 'fv_issues_found', equals: true } },
    { slug: 'issue_urgency', label: 'Urgency', type: 'select',
      options: ['Blocks go-live', 'Nice-to-have'], required: false, group_id: 'issue',
      visible_when: { question: 'fv_issues_found', equals: true } },
    { slug: 'issue_media', label: 'Photo / video of issue', type: 'file', mode: 'observe', required: true, group_id: 'issue',
      visible_when: { question: 'fv_issues_found', equals: true } },
    { slug: 'issue_notes', label: 'Issue notes', type: 'text', required: false, group_id: 'issue',
      visible_when: { question: 'fv_issues_found', equals: true } },
  ]},

  // ── 11 · Unit appliances & amenities (unit_category) ─────────────────────
  { id: '11', label: 'Unit appliances & amenities', scope: 'unit_category', questions: [
    { slug: 'fv_items_to_log', label: 'Any appliances/amenities to log?', type: 'boolean', options: YESNO, required: false,
      description: 'Gate for the item log (separate from the issue log).' },
    { slug: 'item_name', label: 'Item name', type: 'text', required: false, group_id: 'item',
      description: 'Repeat per item in the unit.', visible_when: { question: 'fv_items_to_log', equals: true } },
    { slug: 'item_kind', label: 'Item kind', type: 'select',
      options: ['Appliance', 'Equipment', 'Amenity'], required: false, group_id: 'item',
      visible_when: { question: 'fv_items_to_log', equals: true } },
    { slug: 'item_brand', label: 'Brand / manufacturer', type: 'text', required: false, group_id: 'item',
      visible_when: { question: 'fv_items_to_log', equals: true } },
    { slug: 'item_location', label: 'Location in unit', type: 'text', required: false, group_id: 'item',
      visible_when: { question: 'fv_items_to_log', equals: true } },
    { slug: 'item_instructions', label: 'Operation notes / how to use', type: 'text', required: false, group_id: 'item',
      visible_when: { question: 'fv_items_to_log', equals: true } },
    { slug: 'item_availability_type', label: 'Availability type', type: 'select',
      options: ['Consumable', 'Equipment', 'On Request', 'Fixed'], required: false, group_id: 'item',
      visible_when: { question: 'fv_items_to_log', equals: true } },
    { slug: 'item_video', label: 'How-to-use video', type: 'file', mode: 'observe', required: false, group_id: 'item',
      visible_when: { question: 'fv_items_to_log', equals: true } },
  ]},

  // ── 12 · Unit safety equipment (unit_category) ───────────────────────────
  { id: '12', label: 'Unit safety equipment', scope: 'unit_category', questions: [
    { slug: 'fv_unit_fusebox_present', label: 'Is there a fuse box in the unit?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate (unit-level), mirrors the building question.' },
    { slug: 'fv_unit_fusebox_location', label: 'Unit fuse box location', type: 'text', required: false,
      visible_when: { question: 'fv_unit_fusebox_present', equals: true } },
    { slug: 'fv_unit_fusebox_reset_instructions', label: 'Unit fuse box reset instructions', type: 'text', required: false,
      visible_when: { question: 'fv_unit_fusebox_present', equals: true } },
    { slug: 'fv_fire_extinguisher_present', label: 'Fire extinguisher present in unit?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate: when "No", extinguisher sub-questions collapse.' },
    { slug: 'fv_fire_extinguisher_location', label: 'Fire extinguisher location', type: 'text', required: false,
      visible_when: { question: 'fv_fire_extinguisher_present', equals: true } },
    { slug: 'fv_fire_extinguisher_service_date', label: 'Fire extinguisher last service date visible?', type: 'select',
      options: ['Yes (date)', 'No', 'Expired'], required: false,
      visible_when: { question: 'fv_fire_extinguisher_present', equals: true } },
    { slug: 'fv_smoke_detector_present', label: 'Smoke detector(s) present?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate: when "No", smoke-detector sub-questions collapse.' },
    { slug: 'fv_smoke_detector_working', label: 'Smoke detector functioning (test)', type: 'select',
      options: ['Yes', 'No', 'Could not test'], required: false,
      description: 'Press the test button until it beeps so results are consistent.',
      visible_when: { question: 'fv_smoke_detector_present', equals: true } },
    { slug: 'fv_co_detector_present', label: 'Carbon monoxide detector present?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate: when "No", CO-detector sub-questions collapse.' },
    { slug: 'fv_co_detector_working', label: 'Carbon monoxide detector functioning (test)', type: 'select',
      options: ['Yes', 'No', 'Could not test'], required: false,
      description: 'Use the test button; confirm the alarm sounds.',
      visible_when: { question: 'fv_co_detector_present', equals: true } },
    { slug: 'fv_first_aid_present', label: 'First-aid kit present?', type: 'boolean', options: YESNO, required: true,
      description: 'Gate: when "No", first-aid sub-questions collapse.' },
    { slug: 'fv_first_aid_location', label: 'First-aid kit location', type: 'text', required: false,
      visible_when: { question: 'fv_first_aid_present', equals: true } },
  ]},

  // ── 13 · Unit amenities & details (unit_category) ────────────────────────
  { id: '13', label: 'Unit amenities & details', scope: 'unit_category', questions: [
    { slug: 'fv_blackout_curtains', label: 'Blackout curtains/blinds', type: 'select',
      options: ['All rooms', 'Bedrooms only', 'No'], required: true },
    { slug: 'fv_ceiling_height_m', label: 'Ceiling height (meters)', type: 'number', required: false,
      description: 'Kept where relevant to curtain/blind measurement.' },
  ]},

  // ── 14 · Unit photos & videos (unit_category) ────────────────────────────
  { id: '14', label: 'Unit photos & videos', scope: 'unit_category', questions: [
    { slug: 'fv_photo_bathroom', label: 'Bathroom photos', type: 'file', mode: 'observe', required: true },
    { slug: 'fv_photo_kitchen', label: 'Kitchen photos', type: 'file', mode: 'observe', required: true },
    { slug: 'fv_photo_general_apartment', label: 'General apartment photos', type: 'file', mode: 'observe', required: true },
    { slug: 'fv_photo_window_ceiling', label: 'Window photos for measurement', type: 'file', mode: 'observe', required: false },
  ]},

  // ── 15 · Final assessment / readiness (unit_category) ────────────────────
  { id: '15', label: 'Final assessment / readiness', scope: 'unit_category', questions: [
    { slug: 'fv_readiness_overall', label: 'Overall readiness for go-live', type: 'select',
      options: ['Ready', 'Conditional', 'Not ready'], required: true,
      description: 'Ready = no open issues; Conditional = minor issues with owner actions; Not ready = blocking issues open.' },
    { slug: 'fv_readiness_host_start_date', label: 'Recommended host-start date', type: 'date', required: true,
      description: 'The host-start date is set from this assessment (no predefined go-live date in the new process).' },
    { slug: 'fv_readiness_health_score', label: 'Health score (1-10)', type: 'select',
      options: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], required: true,
      description: 'Composite of condition, completeness, and open-issue count/severity. 10 = move-in ready, 1 = major work needed.' },
    { slug: 'fv_readiness_recommendation_summary', label: 'Summary recommendation', type: 'text', required: false },
    { slug: 'fv_general_comments', label: 'General comments / flags', type: 'text', required: true },
  ]},
];
